# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 719)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(40, 60, 271, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalFrame = QtWidgets.QFrame(self.centralWidget)
        self.verticalFrame.setGeometry(QtCore.QRect(30, 100, 761, 481))
        self.verticalFrame.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.verticalFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QLineEdit(self.verticalFrame)
        self.line.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.line.setAcceptDrops(True)
        self.line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line.setInputMethodHints(QtCore.Qt.ImhPreferUppercase)
        self.line.setAlignment(QtCore.Qt.AlignCenter)
        self.line.setReadOnly(False)
        self.line.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.LIB_L1 = QtWidgets.QLabel(self.verticalFrame)
        self.LIB_L1.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.LIB_L1.setFrameShape(QtWidgets.QFrame.Box)
        self.LIB_L1.setAlignment(QtCore.Qt.AlignCenter)
        self.LIB_L1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LIB_L1.setObjectName("LIB_L1")
        self.verticalLayout.addWidget(self.LIB_L1)
        self.LIB_L2 = QtWidgets.QLabel(self.verticalFrame)
        self.LIB_L2.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.LIB_L2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LIB_L2.setFrameShape(QtWidgets.QFrame.Box)
        self.LIB_L2.setAlignment(QtCore.Qt.AlignCenter)
        self.LIB_L2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LIB_L2.setObjectName("LIB_L2")
        self.verticalLayout.addWidget(self.LIB_L2)
        self.LIB_L3 = QtWidgets.QLabel(self.verticalFrame)
        self.LIB_L3.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.LIB_L3.setFrameShape(QtWidgets.QFrame.Box)
        self.LIB_L3.setAlignment(QtCore.Qt.AlignCenter)
        self.LIB_L3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LIB_L3.setObjectName("LIB_L3")
        self.verticalLayout.addWidget(self.LIB_L3)
        self.LIB_L4 = QtWidgets.QLabel(self.verticalFrame)
        self.LIB_L4.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.LIB_L4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LIB_L4.setAutoFillBackground(False)
        self.LIB_L4.setFrameShape(QtWidgets.QFrame.Box)
        self.LIB_L4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LIB_L4.setAlignment(QtCore.Qt.AlignCenter)
        self.LIB_L4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.LIB_L4.setObjectName("LIB_L4")
        self.verticalLayout.addWidget(self.LIB_L4)
        self.LIB_BADGE = QtWidgets.QLabel(self.centralWidget)
        self.LIB_BADGE.setGeometry(QtCore.QRect(260, 610, 301, 22))
        self.LIB_BADGE.setObjectName("LIB_BADGE")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setGeometry(QtCore.QRect(40, 610, 112, 22))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.LIB_Statut = QtWidgets.QLabel(self.splitter)
        self.LIB_Statut.setObjectName("LIB_Statut")
        self.LIB_COMBO_IMG = QtWidgets.QLabel(self.splitter)
        self.LIB_COMBO_IMG.setObjectName("LIB_COMBO_IMG")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 804, 28))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "The Best GUI Evar!"))
        self.LIB_L1.setText(_translate("MainWindow", "TextLabel"))
        self.LIB_L2.setText(_translate("MainWindow", "TextLabel"))
        self.LIB_L3.setText(_translate("MainWindow", "TextLabel"))
        self.LIB_L4.setText(_translate("MainWindow", "TextLabel"))
        self.LIB_BADGE.setText(_translate("MainWindow", "LIB_BADGE"))
        self.LIB_Statut.setText(_translate("MainWindow", "Statut"))
        self.LIB_COMBO_IMG.setText(_translate("MainWindow", "IMG"))

